/**
 * 通用工具相关API端点
 */
import { API_PREFIX } from './base';

// 通用工具接口
export const UTILS_ENDPOINTS = {
  BASE: `${API_PREFIX}utils`,
  HEALTH_CHECK: `${API_PREFIX}utils/health`,
  VERSION: `${API_PREFIX}utils/version`,
  TIME: `${API_PREFIX}utils/time`,
  TIMEZONE: `${API_PREFIX}utils/timezone`,
  CAPTCHA: `${API_PREFIX}utils/captcha`,
  QR_CODE: `${API_PREFIX}utils/qr-code`,
  BARCODE: `${API_PREFIX}utils/barcode`,
  SMS: `${API_PREFIX}utils/sms`,
  EMAIL: `${API_PREFIX}utils/email`,
  PHONE_VERIFY: `${API_PREFIX}utils/phone-verify`,
  ADDRESS_LOOKUP: `${API_PREFIX}utils/address-lookup`,
  WEATHER: `${API_PREFIX}utils/weather`,
  HOLIDAYS: `${API_PREFIX}utils/holidays`,
  CURRENCY: `${API_PREFIX}utils/currency`,
  UNIT_CONVERT: `${API_PREFIX}utils/unit-convert`,
  VALIDATE: `${API_PREFIX}utils/validate`,
  ENCRYPTION: `${API_PREFIX}utils/encryption`,
  HASH: `${API_PREFIX}utils/hash`,
  RANDOM: `${API_PREFIX}utils/random`,
  UUID: `${API_PREFIX}utils/uuid`,
  SLUG: `${API_PREFIX}utils/slug`,
  PING: `${API_PREFIX}utils/ping`,
  TRACEROUTE: `${API_PREFIX}utils/traceroute`,
  DNS_LOOKUP: `${API_PREFIX}utils/dns-lookup`,
  IP_INFO: `${API_PREFIX}utils/ip-info`,
  URL_SHORTENER: `${API_PREFIX}utils/url-shortener`,
  URL_VALIDATOR: `${API_PREFIX}utils/url-validator`,
  BASE64_ENCODE: `${API_PREFIX}utils/base64-encode`,
  BASE64_DECODE: `${API_PREFIX}utils/base64-decode`,
  JSON_VALIDATOR: `${API_PREFIX}utils/json-validator`,
  XML_VALIDATOR: `${API_PREFIX}utils/xml-validator`,
  CSV_PARSER: `${API_PREFIX}utils/csv-parser`,
  EXCEL_PARSER: `${API_PREFIX}utils/excel-parser`,
  PDF_PARSER: `${API_PREFIX}utils/pdf-parser`,
  IMAGE_OPTIMIZER: `${API_PREFIX}utils/image-optimizer`,
  VIDEO_CONVERTER: `${API_PREFIX}utils/video-converter`,
  AUDIO_CONVERTER: `${API_PREFIX}utils/audio-converter`,
  BACKUP: `${API_PREFIX}utils/backup`,
  RESTORE: `${API_PREFIX}utils/restore`,
  IMPORT: `${API_PREFIX}utils/import`,
  EXPORT: `${API_PREFIX}utils/export`,
  SYNC: `${API_PREFIX}utils/sync`,
  MIGRATION: `${API_PREFIX}utils/migration`,
  MAINTENANCE: `${API_PREFIX}utils/maintenance`,
  CACHE_CLEAR: `${API_PREFIX}utils/cache-clear`,
  LOG_VIEWER: `${API_PREFIX}utils/log-viewer`,
  PERFORMANCE_MONITOR: `${API_PREFIX}utils/performance-monitor`,
  SECURITY_SCAN: `${API_PREFIX}utils/security-scan`,
  AUDIT_LOG: `${API_PREFIX}utils/audit-log`,
} as const;

// 导入导出接口
export const IMPORT_EXPORT_ENDPOINTS = {
  BASE: `${API_PREFIX}import-export`,
  IMPORT_USERS: `${API_PREFIX}import-export/users/import`,
  EXPORT_USERS: `${API_PREFIX}import-export/users/export`,
  IMPORT_STUDENTS: `${API_PREFIX}import-export/students/import`,
  EXPORT_STUDENTS: `${API_PREFIX}import-export/students/export`,
  IMPORT_TEACHERS: `${API_PREFIX}import-export/teachers/import`,
  EXPORT_TEACHERS: `${API_PREFIX}import-export/teachers/export`,
  IMPORT_CLASSES: `${API_PREFIX}import-export/classes/import`,
  EXPORT_CLASSES: `${API_PREFIX}import-export/classes/export`,
  IMPORT_ACTIVITIES: `${API_PREFIX}import-export/activities/import`,
  EXPORT_ACTIVITIES: `${API_PREFIX}import-export/activities/export`,
  IMPORT_ENROLLMENTS: `${API_PREFIX}import-export/enrollments/import`,
  EXPORT_ENROLLMENTS: `${API_PREFIX}import-export/enrollments/export`,
  TEMPLATE_USERS: `${API_PREFIX}import-export/templates/users`,
  TEMPLATE_STUDENTS: `${API_PREFIX}import-export/templates/students`,
  TEMPLATE_TEACHERS: `${API_PREFIX}import-export/templates/teachers`,
  TEMPLATE_CLASSES: `${API_PREFIX}import-export/templates/classes`,
  TEMPLATE_ACTIVITIES: `${API_PREFIX}import-export/templates/activities`,
  TEMPLATE_ENROLLMENTS: `${API_PREFIX}import-export/templates/enrollments`,
  VALIDATE_IMPORT: `${API_PREFIX}import-export/validate`,
  IMPORT_STATUS: (jobId: string) => `${API_PREFIX}import-export/status/${jobId}`,
  EXPORT_STATUS: (jobId: string) => `${API_PREFIX}import-export/status/${jobId}`,
  DOWNLOAD_EXPORT: (jobId: string) => `${API_PREFIX}import-export/download/${jobId}`,
  CANCEL_JOB: (jobId: string) => `${API_PREFIX}import-export/cancel/${jobId}`,
  JOB_HISTORY: `${API_PREFIX}import-export/history`,
  CLEANUP_JOBS: `${API_PREFIX}import-export/cleanup`,
} as const;

// 报表接口
export const REPORT_ENDPOINTS = {
  BASE: `${API_PREFIX}reports`,
  GENERATE: `${API_PREFIX}reports/generate`,
  SCHEDULE: `${API_PREFIX}reports/schedule`,
  TEMPLATES: `${API_PREFIX}reports/templates`,
  HISTORY: `${API_PREFIX}reports/history`,
  DOWNLOAD: (id: number | string) => `${API_PREFIX}reports/${id}/download`,
  PREVIEW: (id: number | string) => `${API_PREFIX}reports/${id}/preview`,
  DELETE: (id: number | string) => `${API_PREFIX}reports/${id}`,
  SHARE: (id: number | string) => `${API_PREFIX}reports/${id}/share`,
  EMAIL: (id: number | string) => `${API_PREFIX}reports/${id}/email`,
  STATUS: (id: number | string) => `${API_PREFIX}reports/${id}/status`,
  CANCEL: (id: number | string) => `${API_PREFIX}reports/${id}/cancel`,
  DUPLICATE: (id: number | string) => `${API_PREFIX}reports/${id}/duplicate`,
  CUSTOM: `${API_PREFIX}reports/custom`,
  BUILDER: `${API_PREFIX}reports/builder`,
  FIELDS: `${API_PREFIX}reports/fields`,
  FILTERS: `${API_PREFIX}reports/filters`,
  CHARTS: `${API_PREFIX}reports/charts`,
  EXPORT_FORMATS: `${API_PREFIX}reports/export-formats`,
  SETTINGS: `${API_PREFIX}reports/settings`,
  PERMISSIONS: `${API_PREFIX}reports/permissions`,
  FAVORITES: `${API_PREFIX}reports/favorites`,
  RECENT: `${API_PREFIX}reports/recent`,
  SEARCH: `${API_PREFIX}reports/search`,
  CATEGORIES: `${API_PREFIX}reports/categories`,
  TAGS: `${API_PREFIX}reports/tags`,
  COMMENTS: (id: number | string) => `${API_PREFIX}reports/${id}/comments`,
  RATINGS: (id: number | string) => `${API_PREFIX}reports/${id}/ratings`,
  USAGE_STATS: `${API_PREFIX}reports/usage-stats`,
  PERFORMANCE: `${API_PREFIX}reports/performance`,
  OPTIMIZATION: `${API_PREFIX}reports/optimization`,
} as const;