#!/bin/bash

# 获取JWT Token的辅助脚本

echo "========================================"
echo "🔑 获取JWT Token"
echo "========================================"
echo ""
echo "方法1: 从浏览器获取 (推荐)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. 打开浏览器访问: http://localhost:5173"
echo "2. 登录系统"
echo "3. 按F12打开开发者工具"
echo "4. 切换到Console标签"
echo "5. 输入以下命令并回车:"
echo ""
echo "   localStorage.getItem('token') || localStorage.getItem('kindergarten_token')"
echo ""
echo "6. 复制返回的token值"
echo "7. 将token粘贴到测试脚本中"
echo ""
echo "========================================"
echo ""

# 方法2：尝试API登录（如果知道用户名密码）
echo "方法2: API直接登录 (可选)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "如果您有测试账号，可以尝试API登录:"
echo ""
echo "curl -X POST http://localhost:3000/api/auth/login \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"username\":\"admin\",\"password\":\"123456\"}'"
echo ""
echo "========================================"
echo ""
echo "获取到token后，请:"
echo "1. 编辑 batch_test_tools.sh"
echo "2. 将 YOUR_JWT_TOKEN 替换为实际token"
echo "3. 运行: ./batch_test_tools.sh"
echo ""
